language:
  - python

# Disable sudo to speed up the build
sudo: false

os: linux

python: 
   - 2.7
   - 3.7

install:
   - pip install psutil

script:
  - python unit_tests.py
  - mkdir in
  - echo AAAAA > in/test
  - mkdir out
  - python manul.py -i in -o out --stop_after_nseconds 7 "linux/test/test_afl @@"
  - ls out/0/crashes/
