# appveyor.yml
---
environment:
  matrix:
    - PYTHONENV: "C:\\Python27"
    - PYTHONENV: "C:\\Python37"

init:
  - "ECHO %PYTHON%"

install:
  - "%PYTHONENV%/Scripts/pip.exe install nose"
  - "%PYTHONENV%/Scripts/pip.exe install coverage"

test_script:
  - "%PYTHONENV%/Scripts/nosetests"
